apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7.28
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: MYSQL_DATABASE
              value: transacoes
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/mysql
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: mysql-claim