kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql
  namespace: infra
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql/"