apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
        - image: luisalexandre/jenkins-with-docker-and-kubectl-and-leiningen-and-sonar-scanner
          name: jenkins
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: jenkins
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /var/jenkins_home
            - name: docker
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-claim