apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: infra
  labels:
    app: jenkins
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
  type: NodePort