#!groovy

node {

    def lein = "lein"

    stage(name: "Git Checkout") {
        checkout scm
    }

    stage(name: "Build/Back") {
        sh "${lein} clean"
        sh "${lein} ring uberjar"
    }

    stage(name: "Run/Test") {
        sh "${lein} with-profile testci midje"
    }



    stage(name: "Run/Cloverage/Test") {
        sh "${lein} with-profile testci cloverage --codecov"
    }

    stage(name: "Inpect/Sonar") {
        withSonarQubeEnv('SonarQube') {
            sh "/opt/sonar-scanner/bin/sonar-scanner"
        }
    }

    stage(name: "Docker/Back/Build"){
        sh "docker build -t luisalexandre/financeiro:latest ."
    }

    stage(name: "Docker/Push") {
        withDockerRegistry(credentialsId: 'dockerhub') {
            sh "docker push luisalexandre/financeiro:latest"
        }
    }

    stage(name: "Docker/RMI") {
      sh "docker rmi -f luisalexandre/financeiro:latest"
    }

    stage(name: "Kubernetes/Deploy") {
        sh "kubectl replace -f deploy/financeiro/deployment.yml --force"
        sh "kubectl replace -f deploy/financeiro/service.yml --force"
    }

}