apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-postgres
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-postgres
  template:
    metadata:
      name: sonarqube-postgres
      labels:
        app: sonarqube-postgres
    spec:
      containers:
        - image: postgres:9.6.5
          name: sonarqube-postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres
                  key: password
            - name: POSTGRES_USER
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: sonarqube-postgres-claim