apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgres
  namespace: infra
  labels:
    app: sonarqube-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: sonarqube-postgres
  type: ClusterIP