apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
    spec:
      containers:
        - image: luisalexandre/sonarqube-with-pluggin-clojure:latest
          name: sonarqube
          imagePullPolicy: Always
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonarqube-postgres:5432/sonar
          ports:
            - containerPort: 9000
              name: sonarqube
          volumeMounts:
            - name: data-disk
              mountPath: /opt/sonarqube/data
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: sonarqube-claim