kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube
  namespace: infra
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sonarqube/"