apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: infra
  labels:
    app: sonarqube
spec:
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 32100
  selector:
    app: sonarqube
  type: NodePort